name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !(github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]'))
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: abatilo/actions-poetry@v2
      - uses: astral-sh/setup-uv@v5
      - run: uv python install
      - run: uv run ruff check .
      - run: uv run pytest --cov=preston --cov-report=xml
      - run: bash <(curl -s https://codecov.io/bash)
