name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !(github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]'))
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install dependencies
        run:  /home/runner/.local/bin/poetry install
      - name: Run tests
        run:  /home/runner/.local/bin/poetry run pytest --cov=preston --cov-report=xml
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
